# Generated by Django 5.2.17 on 2026-09-16 20:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remitente', models.CharField(max_length=150, verbose_name='Remitente')),
                ('asunto', models.CharField(max_length=200, verbose_name='Asunto')),
                ('cuerpo', models.TextField(verbose_name='Cuerpo del mensaje')),
                ('prioridad', models.IntegerField(default=1, verbose_name='Prioridad')),
                ('categoria', models.CharField(choices=[('Ticket crítico', 'Ticket crítico'), ('Requiere firma', 'Requiere firma'), ('Informativo', 'Informativo'), ('Dato inválido', 'Dato inválido')], default='Informativo', max_length=50, verbose_name='Categoría')),
                ('resumen', models.CharField(blank=True, default='', max_length=255, verbose_name='Resumen')),
                ('accion_sugerida', models.CharField(blank=True, default='', max_length=255, verbose_name='Acción sugerida')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de registro')),
                ('eliminado', models.BooleanField(default=False, verbose_name='Eliminado')),
                ('fecha_eliminacion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación')),
            ],
            options={
                'verbose_name': 'Registro de correo',
                'verbose_name_plural': 'Registros de correos',
                'ordering': ['-fecha'],
            },
        ),
    ]
